- lib/build/recipe/emailpassword/components/signInAndUp/themes/default/SignUp.js
- lib/build/recipe/emailpassword/components/signInAndUp/themes/default/SignUpFooter.d.ts
- lib/build/recipe/emailpassword/components/signInAndUp/themes/default/SignUpFooter.js
- lib/build/recipe/emailpassword/styles/styles.js
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/components/superTokensRoute.tsx
- lib/ts/recipe/emailpassword/components/signInAndUp/themes/default/SignUp.tsx
- lib/ts/recipe/emailpassword/components/signInAndUp/themes/default/SignUpFooter.tsx
- lib/ts/recipe/emailpassword/styles/styles.ts
- lib/ts/utils.ts
- test/react-test-app/src/App.js
**privacy and terms links not defined:**
**privacy link only**
**terms link only**
**privacy and terms links**
> 0.0 quick fixes

- lib/build/recipe/emailpassword/components/signInAndUp/SignInAndUp.js
- lib/build/recipe/emailpassword/components/signInAndUp/themes/default/SignUp.js
- lib/build/recipe/emailpassword/components/signInAndUp/themes/default/SignUpFooter.d.ts
- lib/build/recipe/emailpassword/components/signInAndUp/themes/default/SignUpFooter.js
- lib/build/recipe/emailpassword/emailPassword.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/emailpassword/utils.js
- lib/build/recipe/session/session.js
- lib/build/superTokens.js
- lib/ts/recipe/emailpassword/components/signInAndUp/SignInAndUp.tsx
- lib/ts/recipe/emailpassword/components/signInAndUp/themes/default/SignUp.tsx
- lib/ts/recipe/emailpassword/components/signInAndUp/themes/default/SignUpFooter.tsx
- lib/ts/recipe/emailpassword/emailPassword.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/emailpassword/utils.ts
- lib/ts/recipe/session/session.ts
- lib/ts/superTokens.tsx
- test/react-test-app/src/App.js
- test/react-test-app/src/themes/signInAndUp.js
- test/unit/recipe/emailpassword/emailPassword.test.js
- Add links to docs when throwing. https://github.com/supertokens/supertokens-auth-react/issues/23
- Rename termsAndCondition => TermsOfService Fix https://github.com/supertokens/supertokens-auth-react/issues/37
> termsAndConditions => termsOfService

- CONTRIBUTING.md
- lib/build/recipe/session/index.d.ts
- lib/build/recipe/session/session.d.ts
- lib/build/recipe/session/session.js
- lib/ts/recipe/session/index.ts
- lib/ts/recipe/session/session.ts
- test/unit/recipe/emailpassword/emailPassword.test.js
- https://github.com/supertokens/supertokens-auth-react/issues/44
- Removed the instance function `addAxiosInterceptor`. Instead, we are calling the `sessionSdk` directly from the `static` function. This should fix the issue mentioned above.
- Some of the session function signatures were still incorrect. TS did not point it out because the type of `sessionSdk` was `any`. I have changed and fixed those.
- Maybe fixed incorrect statements in the `CONTRIBUTING.md` file 
- I could not get the tests to run because of numerous errors while starting the various processes. 
- The biggest issue I faced was that even after `npm run test` failed, and I quit it, I was getting the message "Waiting for frontend...". This means there were some "orphan" processes running in the background even after I …
> changes to session recipe

- package.json
- test/react-test-app/package.json
> fix package.json dependencies

- .gitignore
- lib/build/recipe/emailpassword/components/features/signInAndUp/SignInAndUp.js
- lib/build/recipe/emailpassword/components/themes/default/signInAndUp/index.d.ts
- lib/build/recipe/emailpassword/components/themes/default/signInAndUp/index.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/emailpassword/utils.js
- lib/ts/recipe/emailpassword/components/features/signInAndUp/SignInAndUp.tsx
- lib/ts/recipe/emailpassword/components/themes/default/signInAndUp/index.tsx
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/emailpassword/utils.ts
- package-lock.json
- test/end-to-end/routing.test.js
- test/end-to-end/signin.test.js
- test/end-to-end/signup.test.js
- test/react-test-app/package-lock.json
- test/server/.gitignore
- test/server/package-lock.json
> 0.2 default to sign up

- lib/build/recipe/emailpassword/components/features/signInAndUp/SignInAndUp.js
- lib/build/recipe/emailpassword/components/themes/default/styles/styles.js
- lib/ts/recipe/emailpassword/components/features/signInAndUp/SignInAndUp.tsx
- lib/ts/recipe/emailpassword/components/themes/default/styles/styles.ts
> 0.2 default to sign up to custom themes

- CHANGELOG.md
- addDevTag
- lib/build/components/superTokensRoute.js
- lib/build/constants.d.ts
- lib/build/constants.js
- lib/build/recipe/emailpassword/components/features/resetPasswordUsingToken/resetPasswordUsingToken.js
- lib/build/recipe/emailpassword/components/themes/default/styles/styles.js
- lib/build/recipe/emailpassword/emailPassword.js
- lib/build/superTokens.js
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/components/superTokensRoute.tsx
- lib/ts/constants.ts
- lib/ts/recipe/emailpassword/components/features/resetPasswordUsingToken/resetPasswordUsingToken.tsx
- lib/ts/recipe/emailpassword/components/themes/default/styles/styles.ts
- lib/ts/recipe/emailpassword/emailPassword.ts
- lib/ts/superTokens.tsx
- lib/ts/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- Better error message for SSR.
- Add margin bottom for general Errors.
- Move react-router-dom to optional dependencies.
- Add check for package-lock version in `addDevTag` script.
Ex with NextJS:
> better error messages for SSR

- eslint/index.js
- eslint/package.json
- lib/.eslintrc.js
- lib/ts/recipe/emailpassword/emailPassword.ts
- lib/ts/superTokens.tsx
- lib/ts/utils.ts
- package-lock.json
- package.json
Create an internal eslint plugin for rules specific to this project.
Reference: https://www.webiny.com/blog/create-custom-eslint-rules-in-2-minutes-e3d41cb6a9a0
> add eslint rule to prevent accessing window object directly

- lib/build/recipe/emailpassword/components/themes/default/styles/styles.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailpassword/components/themes/default/styles/styles.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/react-test-app/package-lock.json
- test/react-test-app/src/App.css
Bring back mobile responsiveness.
Tested in Chrome / Safari / Firefox / Edge
> fix mobile responsiveness

- test/end-to-end/emailverification.test.js
- test/end-to-end/resetpasswordusingtoken.test.js
- test/helpers.js
- test/server/index.js
Fix https://github.com/supertokens/supertokens-auth-react/issues/116
> use createAndSendCustomEmail to get valid tokens

- hooks/pre-commit.sh
- lib/build/recipe/emailpassword/components/styles/styleContext.d.ts
- lib/build/recipe/emailpassword/components/styles/styleContext.js
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/types.d.ts
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/recipe/emailpassword/components/styles/styleContext.tsx
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/types.ts
- lib/ts/utils.ts
- package-lock.json
- package.json
Detect unused methods and types. 
Add to precommit hook to make sure we never release unused methods intentionally.
> prune TS unused types and methods

- CHANGELOG.md
- examples/for-tests/src/App.js
- examples/with-typescript/package.json
- lib/build/normalisedURLPath.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/components/superTokensRoute.tsx
- lib/ts/normalisedURLPath.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/routing.test.js
- test/helpers.js
- test/unit/utils.test.js
The issue happens because react-router-dom:
```js
<Route exact path="">
<div>Test</div>
</div>
```
Behaves as if `path` was not provided. It will catch everything.
By making sure we give it `/` instead ``, we make sure that the bug doesn't happen even when empty `websiteBasePath` is given.
> fix issue with react-router-dom

- examples/with-typescript/src/App.tsx
> change body background when dark theme is selected

- lib/ts/recipe/authRecipeModule/types.ts
- lib/ts/recipe/emailpassword/components/features/signInAndUp/index.tsx
- lib/ts/recipe/emailpassword/types.ts
More auth recipe abstraction to prepare for 3rd party recipe.
> more auth recipe abstraction

- lib/ts/recipe/authRecipeModule/components/themes/signInAndUp/signUpFooter.tsx
- lib/ts/recipe/emailpassword/components/themes/signInAndUp/signUp.tsx
Extract signup footer to authRecipeModule as it will be reused by thirdparty recipe.
> extract signup footer to autthrecipemodule

- lib/build/recipe/thirdparty/components/features/signInAndUp/index.js
- lib/build/recipe/thirdparty/providers/index.d.ts
- lib/build/recipe/thirdparty/providers/index.js
- lib/ts/recipe/thirdparty/components/features/signInAndUp/index.tsx
- lib/ts/recipe/thirdparty/providers/index.tsx
`https://example.com` => `https://example.com/?state=69fb599f405b2111c9b6c&redirect_uri=http%3A%2F%2Flocalhost%3A3031%2Fauth%2Fcallback%2Fgithub`
> add redirect_uri to auth url

- CHANGELOG.md
- examples/for-tests/src/App.js
- frontendDriverInterfaceSupported.json
- lib/build/recipe/thirdparty/index.d.ts
- lib/build/recipe/thirdparty/index.js
- lib/build/recipe/thirdparty/providers/apple.d.ts
- lib/build/recipe/thirdparty/providers/apple.js
- lib/build/recipe/thirdparty/providers/custom.js
- lib/build/recipe/thirdparty/providers/facebook.d.ts
- lib/build/recipe/thirdparty/providers/facebook.js
- lib/build/recipe/thirdparty/providers/github.d.ts
- lib/build/recipe/thirdparty/providers/github.js
- lib/build/recipe/thirdparty/providers/google.d.ts
- lib/build/recipe/thirdparty/providers/google.js
- lib/build/recipe/thirdparty/providers/twitter.d.ts
- lib/build/recipe/thirdparty/providers/twitter.js
- lib/build/recipe/thirdparty/utils.js
- lib/ts/recipe/thirdparty/index.ts
- lib/ts/recipe/thirdparty/providers/apple.tsx
- lib/ts/recipe/thirdparty/providers/custom.tsx
- lib/ts/recipe/thirdparty/providers/facebook.tsx
- lib/ts/recipe/thirdparty/providers/github.tsx
- lib/ts/recipe/thirdparty/providers/google.tsx
- lib/ts/recipe/thirdparty/providers/twitter.tsx
- lib/ts/recipe/thirdparty/thirdparty.ts
- lib/ts/recipe/thirdparty/utils.ts
- test/helpers.js
- test/unit/recipe/emailpassword/thirdParty.test.js
Add tests to ThirdParty configs normalisation.
> add config unit tests for third party

- lib/build/recipe/thirdparty/components/features/signInAndUp/index.js
- lib/build/recipe/thirdparty/providers/index.d.ts
- lib/build/recipe/thirdparty/providers/index.js
- lib/ts/recipe/thirdparty/components/features/signInAndUp/index.tsx
- lib/ts/recipe/thirdparty/providers/index.tsx
Reverts supertokens/supertokens-auth-react#185
> Revert "rm redirect-uri from frontend"

- CHANGELOG.md
- lib/build/recipe/thirdparty/components/features/signInAndUp/index.js
- lib/build/recipe/thirdparty/components/features/signInAndUpCallback/index.js
- lib/build/recipe/thirdparty/providers/index.d.ts
- lib/build/recipe/thirdparty/providers/index.js
- lib/build/recipe/thirdparty/thirdparty.d.ts
- lib/build/recipe/thirdparty/thirdparty.js
- lib/build/recipe/thirdparty/types.d.ts
- lib/ts/recipe/thirdparty/components/features/signInAndUp/index.tsx
- lib/ts/recipe/thirdparty/components/features/signInAndUpCallback/index.tsx
- lib/ts/recipe/thirdparty/providers/index.tsx
- lib/ts/recipe/thirdparty/thirdparty.ts
- lib/ts/recipe/thirdparty/types.ts
- test/end-to-end/thirdparty.test.js
Allow to overwrite the redirect URL For OAuth. Useful for multi tenancy with third party.
> 0.6 get auth redirect uri

- CHANGELOG.md
- CONTRIBUTING.md
- examples/for-tests/package.json
- examples/with-typescript/src/App.tsx
- lib/build/httpRequest.d.ts
- lib/build/httpRequest.js
- lib/build/recipe/authRecipeModule/types.d.ts
- lib/build/recipe/emailpassword/types.d.ts
- lib/build/recipe/recipeModule/types.d.ts
- lib/build/recipe/thirdparty/types.d.ts
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/httpRequest.ts
- lib/ts/recipe/authRecipeModule/types.ts
- lib/ts/recipe/emailpassword/types.ts
- lib/ts/recipe/recipeModule/types.ts
- lib/ts/recipe/thirdparty/types.ts
- lib/ts/utils.ts
Backward compatible update to preapihook to support updating the URL
> 0.7 preapihook

- examples/with-aws-lambda/backend/config.js
- examples/with-aws-lambda/backend/package.json
- examples/with-aws-lambda/frontend/package.json
> aws example updated to latest version of node and auth-react package

- CHANGELOG.md
- frontendDriverInterfaceSupported.json
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/resetpasswordusingtoken.test.js
- test/end-to-end/signin.test.js
- test/end-to-end/signup.test.js
- test/helpers.js
- test/server/package.json
- test/startTestApp.sh
- test/unit/index.test.js
Related to https://github.com/supertokens/supertokens-core/issues/237
> Update to session SDK 

- lib/ts/components/componentOverride/componentOverrideContext.ts
- lib/ts/components/componentOverride/withOverride.tsx
@dulowski-marek  please feel free to merge into your branch once you have reviewed it
Related to: https://github.com/supertokens/supertokens-auth-react/pull/255
> Detects if withOverride is being using without parent provider

- examples/with-localstorage/api-server.js
- examples/with-localstorage/package.json
updated api-server.js for with-localstorage example to use supertokens-node version 7.0
-   #318
> with-localstorage example updated to use supertokens-node version 7.0

- examples/with-aws-lambda/backend/auth.js
- examples/with-aws-lambda/backend/user.js
aws lambda middy fix
-   https://github.com/supertokens/supertokens-node/issues/196
> aws lambda middy fix

- .circleci/config.yml
- CHANGELOG.md
- hooks/pre-commit.sh
- lib/build/components/superTokensRoute.d.ts
- lib/build/components/superTokensRoute.js
- lib/build/recipe/emailpassword/components/features/resetPasswordUsingToken/index.js
- lib/build/recipe/emailpassword/components/features/signInAndUp/index.js
- lib/build/recipe/session/sessionAuth.js
- lib/build/recipe/thirdparty/components/features/signInAndUp/index.js
- lib/build/recipe/thirdpartyemailpassword/components/features/signInAndUp/index.js
- lib/build/superTokens.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/components/superTokensRoute.tsx
- lib/ts/recipe/emailpassword/components/features/resetPasswordUsingToken/index.tsx
- lib/ts/recipe/emailpassword/components/features/signInAndUp/index.tsx
- lib/ts/recipe/session/sessionAuth.tsx
- lib/ts/recipe/thirdparty/components/features/signInAndUp/index.tsx
- lib/ts/recipe/thirdpartyemailpassword/components/features/signInAndUp/index.tsx
- lib/ts/superTokens.tsx
- lib/ts/version.ts
- package-lock.json
- package.json
Removing all circular dependencies
-   #334
No functionality changed, tests should still run. I'll test that it solves the linked issue manually.
No interface changed - no documentation change necessary
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch …
> No circular deps

- .gitignore
- test/end-to-end/passwordless.test.js
- test/server/index.js
A few small fixes as per comments in the passwordless PR
> Pless integration test fixes

- README.md
> Fix the link to discord

- lib/build/recipe/passwordless/components/features/signInAndUp/index.d.ts
- lib/build/recipe/passwordless/components/features/signInAndUp/index.js
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/ts/recipe/passwordless/components/features/signInAndUp/index.tsx
- lib/ts/utils.ts
- test/helpers.js
Fixed a timing issue + improved stability of tests
- 
N/A
N/A
- …
> Fixed timing issue + improved test stability

- test/end-to-end/routing.test.js
- test/end-to-end/signin.test.js
- test/helpers.js
- test/unit/recipe/emailpassword/emailPassword.test.js
- test/unit/recipe/emailpassword/validators.test.js
Fixes test errors introduced in the translatable comps PR
-   #233 
N/A: test fixes
N/A: test fixes
-   If no such branch exists, then create …
> test: fix translation tests

- .github/helpers/.gitignore
- .github/helpers/package.json
- .github/workflows/tests-pass-check-pr.yml
- .github/workflows/tests.yml
- Adds a Github workflow to run all tests
- Adds a Github workflow to check if tests pass and adds the helper project to import the test-pass-check script from github-workflow-helpers
- 
- The Github action succeeds on the forked repository
None
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and …
> chore: Add Github Action to run tests and a PR action to check if tests pass

- CHANGELOG.md
- lib/build/recipe/emailpassword/components/library/formBase.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailpassword/components/library/formBase.tsx
- lib/ts/version.ts
- package-lock.json
- package.json
- test/with-typescript/package-lock.json
Fix an issue in the form base component when it would stop working if mounted twice.
We should test in Next in the future, but nothing new right now.
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest …
> fix: form base nextjs bug

- CHANGELOG.md
- lib/build/recipe/emailverification/components/themes/emailVerification/sendVerifyEmail.js
- lib/build/recipe/emailverification/components/themes/emailVerification/verifyEmailLinkClicked.js
- lib/ts/recipe/emailverification/components/themes/emailVerification/sendVerifyEmail.tsx
- lib/ts/recipe/emailverification/components/themes/emailVerification/verifyEmailLinkClicked.tsx
- package-lock.json
- package.json
- test/end-to-end/emailverification.test.js
- test/helpers.js
Handles general errors and displays the error message from the API for email verification flows
-  https://github.com/supertokens/for-zenhub/issues/28
All existing test cases should pass
WIP
-   [ ] ~~Changelog has been updated~~
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `lib/ts/version.ts`~~
-   [ ] ~~Changes to the version if needed~~
-   ~~In `package.json`~~
-   ~~In `package-lock.json`~~
-   ~~In `lib/ts/version.ts`~~
-   [ ] ~~Issue this PR against the latest non released version branch.~~
-   ~~To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest …
> refactor: Add general error handling for email verification

- CHANGELOG.md
- lib/build/recipe/emailverification/components/features/emailVerification/index.d.ts
- lib/build/recipe/emailverification/components/features/emailVerification/index.js
- lib/build/recipe/emailverification/components/themes/emailVerification/sendVerifyEmail.js
- lib/build/recipe/emailverification/components/themes/emailVerification/verifyEmailLinkClicked.js
- lib/build/recipe/emailverification/emailVerificationAuth.js
- lib/build/recipe/passwordless/components/features/linkClickedScreen/index.js
- lib/build/recipe/passwordless/components/themes/signInUp/userInputCodeForm.js
- lib/build/recipe/session/sessionAuth.js
- lib/build/recipe/thirdparty/components/features/signInAndUpCallback/index.d.ts
- lib/build/recipe/thirdparty/components/features/signInAndUpCallback/index.js
- lib/build/types.d.ts
- lib/build/utils.d.ts
- lib/build/utils.js
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/recipe/emailverification/components/features/emailVerification/index.tsx
- lib/ts/recipe/emailverification/components/themes/emailVerification/sendVerifyEmail.tsx
- lib/ts/recipe/emailverification/components/themes/emailVerification/verifyEmailLinkClicked.tsx
- lib/ts/recipe/emailverification/emailVerificationAuth.tsx
- lib/ts/recipe/passwordless/components/features/linkClickedScreen/index.tsx
- lib/ts/recipe/passwordless/components/themes/signInUp/userInputCodeForm.tsx
- lib/ts/recipe/session/sessionAuth.tsx
- lib/ts/recipe/thirdparty/components/features/signInAndUpCallback/index.tsx
- lib/ts/types.ts
- lib/ts/utils.ts
- lib/ts/version.ts
- package-lock.json
- package.json
Fixes for running in react 18 strict mode dev.
-   #428
No functionality change, tests are updated in a separate PR
No functionality change
- …
> feat: add support for react@18

- CHANGELOG.md
- examples/with-thirdpartypasswordless-electron/package.json
- lib/build/version.d.ts
- lib/build/version.js
- lib/ts/version.ts
- package-lock.json
- package.json
> Dependencies fix

- .github/workflows/pre-commit-hook-run.yml
> adds new pr check for pre commit

- examples/with-supabase/config/backendConfig.ts
- Fixs comments in Supabase integration app
-   none
- none
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch …
> chore: fix comments in supabase intergration app

- .github/workflows/pre-commit-hook-run.yml
Fixes the pre commut github action so that npm install does not fail
- ...
No code changes
None needed
-   If no such branch exists, then …
> chore: Update pre commit github action

- examples/with-emailpassword-vercel/api/index.js
- examples/with-emailpassword/api-server.js
- examples/with-emailverification-then-password-thirdpartyemailpassword/api-server.js
- examples/with-i18next/api-server.js
- examples/with-localstorage/api-server.js
- examples/with-no-session-on-sign-up-thirdpartyemailpassword/api-server/index.js
- examples/with-one-login-many-subdomains/api-server.js
- examples/with-one-login-per-subdomain/api-server.js
- examples/with-passwordless/api-server/index.js
- examples/with-phone-password/api-server/index.ts
- examples/with-sign-in-up-split-emailpassword/api-server.js
- examples/with-thirdparty-2fa-passwordless/api-server/index.js
- examples/with-thirdparty/api-server.js
- examples/with-thirdpartyemailpassword-passwordless/api-server/index.js
- examples/with-thirdpartyemailpassword/api-server.js
- examples/with-thirdpartypasswordless-electron/api-server/index.js
- examples/with-thirdpartypasswordless/api-server/index.js
Adds comment about sessioninfo being an example API
> docs: changes comment over example API in example apps

- package.json
> chore: Update size limit

- .circleci/markTesting.sh
> chore: Update api version for markTesting

- examples/with-phone-password/package.json
- examples/with-phone-password/src/App.tsx
- examples/with-phone-password/src/PhoneVerification/Footer.tsx
- examples/with-phone-password/src/PhoneVerification/index.tsx
- examples/with-thirdparty-2fa-passwordless/package.json
- examples/with-thirdparty-2fa-passwordless/src/App.js
- examples/with-thirdparty-2fa-passwordless/src/SecondFactor/index.js
- lib/build/recipe/session/recipe.js
- lib/build/recipe/session/types.d.ts
- lib/ts/recipe/session/recipe.ts
- lib/ts/recipe/session/types.ts
- package-lock.json
- package.json
- test/with-typescript/src/App.tsx
> chore: Use latest web-js sdk and update example apps to use user context

- .github/workflows/tests.yml
- package-lock.json
- package.json
> chore: Use latest supertokens-web-js

- CHANGELOG.md
- examples/with-angular-thirdpartyemailpassword/src/app/auth/auth.component.ts
fixs for angular app, removes unnecessary lifecycle hook(ngOnChange)
-   none
- manual testing
-none 
-   ~~[ ] `frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `lib/ts/version.ts`~~
-   ~~[ ] Changes to the version if needed~~
-   ~~In `package.json`~~
-   ~~In `package-lock.json`~~
-   ~~In `lib/ts/version.ts`~~
-   If no such …
> fix: Angular app fixs

- test/end-to-end/generalerror.test.js
- Add missing test cleanup
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-auth-react/2323/workflows/bbb52005-c76b-4931-87ef-fdaf668d53de/jobs/717
Test/CI only change
Test/CI only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …
> test: fix missing test cleanups

- CHANGELOG.md
- lib/build/recipe/userroles/index.d.ts
- lib/build/recipe/userroles/index.js
- lib/ts/recipe/userroles/index.ts
- recipe/userroles/index.d.ts
- recipe/userroles/index.js
- test/with-typescript/src/App.tsx
Re-exported user role related claims
-   
Added type test into `with-typescript`
Done later
-   If no such branch exists, then create one from …
> feature: User role related claims

- CHANGELOG.md
Updated changelog with related migration info/snippet.
-   
Done separately #532 
Done separately
-   If no such branch exists, then create one …
> chore: add changelog for session claims/email verification

- test/end-to-end/emailverification.test.js
- test/end-to-end/passwordless.test.js
- test/end-to-end/signup.test.js
- test/end-to-end/userroles.test.js
- test/helpers.js
- test/server/index.js
- test/unit/recipe/emailpassword/emailPassword.test.js
- test/unit/recipe/session/sessionAuth.test.tsx
Adds tests for user roles related claims
Adds a few simple tests that read/validate claims on the frontend
N/A
-   If no such branch exists, …
> test: user roles claim

- CHANGELOG.md
- test/unit/exports.test.tsx
- Adds unit tests to make sure that recipe functions and components are exported correctly
-   If no such branch exists, then create one from …
> chore: Add tests to make sure recipe functions are exported correctly

- examples/with-phone-password/README.md
README.md fixes in example app
-   [ ] …
> docs: readme fixes in phone-password example app

- examples/with-phone-password/README.md
- examples/with-phone-password/api-server/index.ts
- examples/with-thirdpartyemailpassword-2fa-passwordless/api-server/index.ts
- examples/with-thirdpartyemailpassword-2fa-passwordless/src/App.tsx
Minor README/comment updates for the related docs PR + unused code removed
-   supertokens/docs#440
N/A
N/A
-   If no such branch exists, then …
> docs: example docs update

- CHANGELOG.md
- examples/with-emailpassword/api-server.js
- examples/with-emailpassword/package.json
- examples/with-passwordless/api-server/index.js
- examples/with-passwordless/package.json
- examples/with-thirdparty/api-server.js
- examples/with-thirdparty/package.json
- examples/with-thirdpartyemailpassword/api-server.js
- examples/with-thirdpartyemailpassword/package.json
- examples/with-thirdpartypasswordless/api-server/index.js
- examples/with-thirdpartypasswordless/package.json
- Changes the supertokens-node version for primary example apps
- Adds the dashboard recipe for primary example apps
-   
-   [x] Had …
> chore: Update supertokens-node dependency version for example apps

- test/end-to-end/emailverification.test.js
Fixes test flakiness in deleted user email verification test
-   
N/A
N/A
-   [x] If added a new recipe interface, then …
> test: fix console log normalisation

- lib/build/recipe/passwordless/components/themes/signInUp/emailOrPhoneForm.js
- lib/ts/recipe/passwordless/components/themes/signInUp/emailOrPhoneForm.tsx
fixed memory leak warning in emailOrPhoneForm
-   #603 
N/A
N/A
-   [ ] If added a new recipe interface, then make sure …
> fix: memory leak warning from last pr

- test/unit/utils.test.tsx
Update unit test file to ts
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-auth-react/3129/workflows/727769c4-6c21-41d4-8092-1dec2a6ad4bd/jobs/1792/parallel-runs/1
test only change
test only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> test: update unit test

- hooks/pre-commit.sh
- test/unit/index.test.ts
updated test to ts + fixed pre-commit hook version detection
Test only change
Test only change
-   If no such branch exists, then create one from the …
> test: updated test to ts + fixed pre-commit hook version detection

- examples/with-aws-lambda/frontend/package.json
- examples/with-cli-login/package.json
- examples/with-emailpassword-vercel/package.json
- examples/with-emailpassword/package.json
- examples/with-emailverification-then-password-thirdpartyemailpassword/package.json
- examples/with-emailverification-with-otp/package.json
- examples/with-hasura-thirdpartyemailpassword/package.json
- examples/with-i18next/package.json
- examples/with-jwt-localstorage/package.json
- examples/with-localstorage/package.json
- examples/with-multiple-email-sign-in/package.json
- examples/with-netlify/package.json
- examples/with-next-iframe/package.json
- examples/with-no-session-on-sign-up-thirdpartyemailpassword/package.json
- examples/with-okta-multi-tenant-pkce-flow/package.json
- examples/with-one-login-many-subdomains/frontend/package.json
- examples/with-one-login-per-subdomain/package.json
- examples/with-passwordless/package.json
- examples/with-phone-password/package.json
- examples/with-sign-in-up-split-emailpassword/package.json
- examples/with-supabase/package.json
- examples/with-svelte-react-thirdpartyemailpassword/package.json
- examples/with-thirdparty/package.json
- examples/with-thirdpartyemailpassword-2fa-passwordless/package.json
- examples/with-thirdpartyemailpassword-passwordless/package.json
- examples/with-thirdpartyemailpassword/package.json
- examples/with-thirdpartypasswordless-electron/package.json
- examples/with-thirdpartypasswordless/package.json
chore: update auth-react dependency version in example apps
-   
Only example dependency update
Only example dependency update
-   If no such branch exists, then create one from the latest released …
> chore: update auth-react dependency version in example apps

- examples/with-aws-lambda/backend/package.json
- examples/with-cli-login/package.json
- examples/with-emailpassword-vercel/package.json
- examples/with-emailpassword/package.json
- examples/with-emailverification-then-password-thirdpartyemailpassword/package.json
- examples/with-emailverification-with-otp/package.json
- examples/with-hasura-thirdpartyemailpassword/package.json
- examples/with-i18next/package.json
- examples/with-jwt-localstorage/package.json
- examples/with-localstorage/package.json
- examples/with-multiple-email-sign-in/package.json
- examples/with-netlify/package.json
- examples/with-next-iframe/package.json
- examples/with-no-session-on-sign-up-thirdpartyemailpassword/package.json
- examples/with-one-login-many-subdomains/package.json
- examples/with-one-login-per-subdomain/package.json
- examples/with-passwordless/package.json
- examples/with-phone-password/package.json
- examples/with-sign-in-up-split-emailpassword/package.json
- examples/with-supabase/package.json
- examples/with-svelte-react-thirdpartyemailpassword/package.json
- examples/with-thirdparty/package.json
- examples/with-thirdpartyemailpassword-2fa-passwordless/package.json
- examples/with-thirdpartyemailpassword-passwordless/package.json
- examples/with-thirdpartyemailpassword/package.json
- examples/with-thirdpartypasswordless-electron/package.json
- examples/with-thirdpartypasswordless/package.json
- test/server/package.json
> chore: update node version in example apps

- examples/for-tests-react-16/src/AppWithReactDomRouter.js
- examples/for-tests-react-16/src/AppWithReactDomRouterV5.js
- test/server/package-lock.json
- test/server/package.json
test: fix typo in reacy16 test app + update SDK version in test server
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-auth-react/3417/workflows/569f603d-e990-45e0-aa78-5bbc3e25f02e/jobs/1914
N/A
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …
> test: fix typo in reacy16 test app + update SDK version in test server

- examples/for-tests-react-16/src/AppWithoutRouter.js
Fix react16 test app
Re-ran all react 16 test locally
-   [ ] Issue this PR against the latest non …
> test: fix react16 test app

- examples/with-aws-lambda/frontend/package.json
- examples/with-cli-login/package.json
- examples/with-emailpassword-vercel/package.json
- examples/with-emailverification-then-password-thirdpartyemailpassword/package.json
- examples/with-emailverification-with-otp/package.json
- examples/with-hasura-thirdpartyemailpassword/package.json
- examples/with-i18next/package.json
- examples/with-jwt-localstorage/package.json
- examples/with-multiple-email-sign-in/package.json
- examples/with-netlify/package.json
- examples/with-next-iframe/package.json
- examples/with-no-session-on-sign-up-thirdpartyemailpassword/package.json
- examples/with-okta-multi-tenant-pkce-flow/package.json
- examples/with-one-login-many-subdomains/frontend/package.json
- examples/with-one-login-per-subdomain/package.json
- examples/with-phone-password/package.json
- examples/with-sign-in-up-split-emailpassword/package.json
- examples/with-supabase/package.json
- examples/with-svelte-react-thirdpartyemailpassword/package.json
- examples/with-thirdpartyemailpassword-2fa-passwordless/package.json
- examples/with-thirdpartyemailpassword-passwordless/package.json
- examples/with-thirdpartypasswordless-electron/package.json
chore: update SDK version in examples …
> chore: update SDK version in examples

- examples/with-thirdparty-google-onetap/README.md
> fix: one tap readme update

- examples/with-update-email-post-verification/backend/index.ts
> fix: remove unnecessary section from code

- examples/with-cli-login/api-server/index.ts
- examples/with-emailverification-then-password-thirdpartyemailpassword/api-server.js
- examples/with-emailverification-with-otp/README.md
- examples/with-emailverification-with-otp/api-server/server.ts
- examples/with-hasura-thirdpartyemailpassword/api-server.js
- examples/with-i18next/api-server.js
- examples/with-no-session-on-sign-up-thirdpartyemailpassword/api-server/index.js
- examples/with-phone-password/api-server/index.ts
- examples/with-phone-password/package.json
- examples/with-supabase/config/backendConfig.ts
- examples/with-svelte-react-thirdpartyemailpassword/server.js
- examples/with-thirdparty-google-onetap/backend/config.ts
- examples/with-thirdparty-google-onetap/backend/package.json
- examples/with-thirdparty-google-onetap/frontend/src/App.tsx
- examples/with-thirdparty-google-onetap/frontend/src/config.tsx
- examples/with-thirdparty-popup/README.md
- examples/with-thirdparty-popup/backend/config.ts
- examples/with-thirdparty-popup/backend/package.json
- examples/with-thirdparty-popup/frontend/package.json
- examples/with-thirdparty-popup/frontend/src/App.tsx
- examples/with-thirdparty-popup/frontend/src/Home/index.tsx
- examples/with-thirdpartyemailpassword-2fa-passwordless/api-server/index.ts
- examples/with-thirdpartyemailpassword-passwordless/api-server/index.ts
- examples/with-thirdpartypasswordless-electron/api-server/index.js
- examples/with-thirdpartypasswordless-electron/src/renderer.tsx
- examples/with-update-email-post-verification/backend/index.ts
- package-lock.json
- package.json
build: update web-js version & revert example updates until release
-   [ ] Issue this PR against …
> chore: update web-js version & revert example updates until dep release

- CHANGELOG.md
This adds some examples to the changelog
> docs: add code example for changelog

- CHANGELOG.md
- addDevTag
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/emailverification.test.js
> fix: Fix e2e tests

- CHANGELOG.md
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
> fix: Fix cicd

- test/prepTestApp.sh
> fix: Update CICD

- webJsInterfaceSupported.json
> chore: update supported webjsinterface version

- CHANGELOG.md
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/emailverification.test.js
- test/end-to-end/multitenancy.dynamic_login_methods.test.js
- test/end-to-end/multitenancy.tenant_interactions.test.js
- test/end-to-end/passwordless.test.js
- test/helpers.js
> test: update tests to make them pass with the next node version

- test/end-to-end/multitenancy.dynamic_login_methods.test.js
> test: fix tests in fe sdk ci

- test/end-to-end/multitenancy.tenant_interactions.test.js
test: re-enable password reset MT test
-   
Test only change
Test only change
-   [ ] If added a new recipe interface, then …
> test: re-enable password reset MT test

- CHANGELOG.md
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/thirdpartypasswordless.pwless.test.js
- test/end-to-end/thirdpartypasswordless.test.js
- test/end-to-end/thirdpartypasswordless.tp.test.js
- test/server/index.js
test: split tppwless tests into multiple files to help with parallelization
-   
N/A, test only change
N/A, test only change
-   If no such branch exists, then create one from the latest released …
> test: split tppwless tests into multiple files to help with parallelization

- test/unit/recipe/thirdparty/signInUp.test.tsx
* feat: add logo property custom providers
* bump version to v0.35.1
* test: custom icons for custom thirdparty providers
* test: add more tests
* bump v0.35.3## Summary of change
- …
> fix: failing tests

- CHANGELOG.md
- examples/with-netlify/package.json
update dev/start script in netlify example
-   
Covered by example tests (GH Action)
N/A
-   [x] If added a new recipe …
> docs(example): update dev/start script in netlify example

- CHANGELOG.md
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/emailverification.test.js
Updated test expectations to match fix in the node behaviour of the emailVerifyGET endpoint
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-node/4586/workflows/d05dcfdc-54d3-4b20-9b57-12adf4f79bc4/jobs/2293
Test only change
Test only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch …
> test: update for new node version

- CHANGELOG.md
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/emailverification.test.js
> test: update test expectations to match new node version

- lib/build/emailpassword-shared7.js
- lib/build/passwordless-shared3.js
- lib/build/thirdparty-shared2.js
- lib/ts/recipe/emailpassword/components/features/signInAndUp/index.tsx
- lib/ts/recipe/passwordless/components/features/linkClickedScreen/index.tsx
- lib/ts/recipe/passwordless/components/features/signInAndUp/index.tsx
- lib/ts/recipe/thirdparty/components/features/signInAndUpCallback/index.tsx
- package-lock.json
- package.json
- test/server/package-lock.json
- test/server/package.json
> fix: update dependency branch names and fix example test issues

- lib/build/genericComponentOverrideContext.js
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/accountlinking.test.js
> test: update tests to pass with new node version as well

- test/end-to-end/accountlinking.test.js
- test/end-to-end/mfa.chooserscreen.test.js
- test/end-to-end/mfa.default_reqs.test.js
- test/end-to-end/mfa.factorscreen.otp.test.js
- test/end-to-end/mfa.factorscreen.totp.test.js
- test/end-to-end/mfa.helpers.js
test: update tests to fix CI
- Removes a skipped test
- Removes an unnecessary TODO
- Adds missing var declarations
-   [ ] Had installed and ran the …
> test: update tests to fix CI

- test/end-to-end/mfa.chooserscreen.test.js
- test/end-to-end/mfa.factorscreen.otp.test.js
- test/end-to-end/mfa.factorscreen.totp.test.js
- test/end-to-end/mfa.requirement_handling.test.js
- test/server/package-lock.json
> test: fix mfa tests

- .github/workflows/chromatic.yml
- package.json
> ci: add chromatic GH action

- examples/with-emailverification-then-password-thirdpartyemailpassword/api-server.js
- examples/with-emailverification-with-otp/api-server/server.ts
- examples/with-emailverification-with-otp/package.json
- examples/with-emailverification-with-otp/test/basic.test.js
- examples/with-phone-password-mfa/api-server/index.ts
- examples/with-phone-password-mfa/test/basic.test.js
- examples/with-phone-password/api-server/index.ts
> examlpe app fix

- examples/with-account-linking/backend/config.ts
- examples/with-account-linking/backend/index.ts
- examples/with-account-linking/frontend/src/LinkingPage/index.tsx
- examples/with-account-linking/package.json
- examples/with-account-linking/test/basic.test.js
> Updates with account linking example app

- examples/with-thirdpartypasswordless-electron/api-server/index.js
- examples/with-thirdpartypasswordless-electron/src/renderer.tsx
Related to: https://github.com/supertokens/supertokens-auth-react/issues/808
> example app fix

- CHANGELOG.md
- lib/build/genericComponentOverrideContext.js
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/prepTestApp.sh
ci: fix dependency issue in CI …
> ci: fix dependency issue in CI

- test/end-to-end/multitenancy.dynamic_login_methods.test.js
- test/helpers.js
> test: make tests more stable

- CHANGELOG.md
- lib/build/genericComponentOverrideContext.js
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/multitenancy.dynamic_login_methods.test.js
- test/helpers.js
> test: backport stability fixes

- .circleci/publish.sh
ci: update chromatic on publish …
> ci: update chromatic on publish

- .circleci/publish.sh
- CHANGELOG.md
- lib/build/genericComponentOverrideContext.js
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
[ci: fix publish script deploying to chromatic](https://github.com/supertokens/supertokens-auth-react/commit/3923076cce5d156cfbf0f806a90f0ed8fc637d96)
-   [ ] Had run `npm run …
> ci: fix publish script deploying to chromatic

- CHANGELOG.md
- lib/build/genericComponentOverrideContext.js
- lib/build/version.d.ts
- lib/ts/version.ts
- package-lock.json
- package.json
- test/end-to-end/accountlinking.test.js
> fix: e2e for 0.38

- test/end-to-end/accountlinking.test.js
> fix: e2e test

- CHANGELOG.md
- lib/build/genericComponentOverrideContext.js
- lib/build/index2.js
- lib/build/version.d.ts
- lib/ts/recipe/authRecipe/components/feature/authPage/authPage.tsx
- lib/ts/version.ts
- package-lock.json
- package.json
Reverts supertokens/supertokens-auth-react#846
> Revert "fix: improve error messages when the authpage has issues covering all factors"

- CHANGELOG.md
- lib/build/genericComponentOverrideContext.js
- lib/build/index2.js
- lib/build/version.d.ts
- lib/ts/recipe/authRecipe/components/feature/authPage/authPage.tsx
- lib/ts/version.ts
- package-lock.json
- package.json
re-creating #846 after wrong merge. …
> fix: improve firstfactor error msg

- test/end-to-end/getRedirectionURL.test.js
- test/end-to-end/mfa.signin.test.js
> fix: failing auth-react tests [0.48]

- test/end-to-end/generalerror.test.js
- test/end-to-end/getRedirectionURL.test.js
- test/end-to-end/thirdpartyemailpassword.test.js
- test/helpers.js
> fix: failing auth-react tests [0.34]
