supertokens/supertokens-auth-react

lib/build/recipe/emailpassword/components/themes/default/library/FormBase.js
lib/build/recipe/emailpassword/components/themes/default/library/input.d.ts
lib/build/recipe/emailpassword/components/themes/default/library/input.js
lib/build/recipe/emailpassword/types.d.ts
lib/build/recipe/emailpassword/utils.js
lib/build/types.d.ts
lib/ts/recipe/emailpassword/components/themes/default/library/FormBase.tsx
lib/ts/recipe/emailpassword/components/themes/default/library/input.tsx
lib/ts/recipe/emailpassword/types.ts
lib/ts/recipe/emailpassword/utils.ts
lib/ts/types.ts
test/helpers.js
test/unit/recipe/emailpassword/emailPassword.test.js

Add autocomplete for Chrome/Safari/Opera
They do not all support new password but they support "email" and "current-password"
Firefox does not need any indication. Firefox finds out on its own the correct behaviour!

autocomplete email and password

---

lib/build/recipe/emailpassword/components/features/signInAndUp/SignInAndUp.d.ts
lib/build/recipe/emailpassword/components/features/signInAndUp/SignInAndUp.js
lib/build/recipe/emailpassword/components/library/FormBase.js
lib/build/recipe/emailpassword/components/themes/default/resetPasswordUsingToken/enterEmail.js
lib/build/recipe/emailpassword/components/themes/default/resetPasswordUsingToken/submitNewPassword.js
lib/build/recipe/emailpassword/components/themes/default/signInAndUp/SignIn.js
lib/build/recipe/emailpassword/components/themes/default/signInAndUp/SignUp.js
lib/build/recipe/emailpassword/types.d.ts
lib/ts/recipe/emailpassword/components/features/signInAndUp/SignInAndUp.tsx
lib/ts/recipe/emailpassword/components/library/FormBase.tsx
lib/ts/recipe/emailpassword/components/themes/default/resetPasswordUsingToken/enterEmail.tsx
lib/ts/recipe/emailpassword/components/themes/default/resetPasswordUsingToken/submitNewPassword.tsx
lib/ts/recipe/emailpassword/components/themes/default/signInAndUp/SignIn.tsx
lib/ts/recipe/emailpassword/components/themes/default/signInAndUp/SignUp.tsx
lib/ts/recipe/emailpassword/types.ts

- Refactoring to merge user provided form field `validate` method for email with `validateEmail` API Call to verify if an email exists.
That way, the theme can validate on blur using only `field.validate` method.
Changes to what we decided in our call:
- We keep the validation when SignUp except that **we do not check if email exists when signUp is clicked**
The reasons for this choice are:
- We still validate the last focused input, so if there is an error here that can be catch by validators, there is no API call.
- All the default validators are not async, so the time taken by this extra check is negligible.
- **Most importantly**, if someone implements the a custom theme, they shouldn't have to run the validation themselves if they do not want to validate on blur. This should still be …

no validateOnBlur method given to themes

---

lib/babel.config.js
lib/build/recipe/emailpassword/types.d.ts
lib/build/recipe/emailpassword/utils.js
lib/ts/recipe/emailpassword/types.ts
lib/ts/recipe/emailpassword/utils.ts

I've tested that it does not impact any other browser than IE.
I've tested that the code used to detect IE works properly (using https://www.browserling.com/).
I haven't successfully tested that the library works on IE11 since my test app does not work in IE11 (even without Supertokens). IE does not really work with react (see https://github.com/supertokens/supertokens-auth-react/issues/99).

always disable shadow DOM for IE

---

lib/build/recipe/emailpassword/components/themes/default/styles/styles.js
lib/ts/recipe/emailpassword/components/themes/default/styles/styles.ts

Fix https://github.com/supertokens/supertokens-core/issues/162

add right padding to input

---

CHANGELOG.md
lib/build/recipe/emailpassword/components/themes/default/styles/styles.js
lib/build/version.d.ts
lib/build/version.js
lib/ts/recipe/emailpassword/components/themes/default/styles/styles.ts
lib/ts/version.ts
package-lock.json
package.json
test/react-test-app/src/App.css

Because of the last PR using `maxWidth` to define the container's width (`in 0.4.1`), the form is getting squashed when wrapped in a html tag that uses `display:flex`. 
This fixes to make sure the width is always as expected. This PR keeps the mobile responsiveness introduced in `0.4.1` but also fixes this issue.

fix width issue when wrapped in display flex container

---

eslint/index.js
lib/.eslintrc.js
lib/build/components/featureWrapper.js
lib/build/recipe/emailpassword/components/features/resetPasswordUsingToken/index copy.d.ts
lib/build/recipe/emailpassword/components/features/resetPasswordUsingToken/index copy.js
lib/build/recipe/emailpassword/components/features/resetPasswordUsingToken/wrapper.d.ts
lib/build/recipe/emailpassword/components/features/resetPasswordUsingToken/wrapper.js
lib/build/recipe/emailpassword/components/features/signInAndUp/index.d.ts
lib/build/recipe/emailpassword/components/features/signInAndUp/index.js
lib/build/recipe/emailpassword/components/features/signInAndUp/wrapper.d.ts
lib/build/recipe/emailpassword/components/features/signInAndUp/wrapper.js
lib/build/recipe/emailpassword/emailPassword.js
lib/build/recipe/emailpassword/index.d.ts
lib/build/recipe/emailpassword/index.js
lib/build/recipe/thirdparty/index.js
lib/build/recipe/thirdpartyemailpassword/components/features/resetPaswsordUsingToken/index.d.ts
lib/build/recipe/thirdpartyemailpassword/components/features/resetPaswsordUsingToken/index.js
lib/build/recipe/thirdpartyemailpassword/thirdpartyEmailpassword.js
lib/ts/components/featureWrapper.tsx
lib/ts/recipe/emailpassword/components/features/resetPasswordUsingToken/index.tsx
lib/ts/recipe/emailpassword/components/features/resetPasswordUsingToken/wrapper.tsx
lib/ts/recipe/emailpassword/components/features/signInAndUp/index.tsx
lib/ts/recipe/emailpassword/components/features/signInAndUp/wrapper.tsx
lib/ts/recipe/emailpassword/emailPassword.ts
lib/ts/recipe/emailpassword/index.ts
lib/ts/recipe/thirdparty/index.ts
lib/ts/recipe/thirdpartyemailpassword/thirdpartyEmailpassword.ts

Make sure that emotion `jsx` is imported as the first import when used in a file.
Fix issue with embedding components in a page.

add linter rules to make sure jsx is the first import

---

CHANGELOG.md
frontendDriverInterfaceSupported.json
lib/build/version.d.ts
lib/build/version.js
lib/build/version.js.map
lib/ts/version.ts
package-lock.json
package.json

- Changes the package version to 0.15.10
- Adds FDI 1.9 to supported FDI versions (both frontendDriverInterfaceSupported.json and version.ts)
- Changed `init` script in package.json to include running `npm i -d` in `test/with-typescript`
- https://github.com/supertokens/for-zenhub/issues/38
No tests needed as there is no logical change
None
- …

Bump version to 0.15.10 and add FDI 1.9 to supported FDI versions

---

CHANGELOG.md
CONTRIBUTING.md
lib/build/recipe/thirdparty/components/library/providerButton.js
lib/build/recipe/thirdparty/components/themes/styles.js
lib/build/version.d.ts
lib/build/version.js
lib/ts/recipe/thirdparty/components/library/providerButton.tsx
lib/ts/recipe/thirdparty/components/themes/styles.ts
lib/ts/version.ts
package-lock.json
package.json

- Changes the provider button component to render the left div (used as the logo container) only if a logo component is provided. Previously this would render an empty div, resulting in the text never being centered.
- Changes the styling for the provider button to handle size changes because of large font sizes or long texts
- Updates the CONTRIBUTING guide
- https://github.com/supertokens/supertokens-auth-react/issues/348
Tested with the sample application in the repo.
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in …

Fix text centering for custom provider buttons

---

CHANGELOG.md
lib/build/recipe/emailpassword/components/library/label.js
lib/build/recipe/emailpassword/components/themes/resetPasswordUsingToken/resetPasswordEmail.js
lib/build/recipe/emailpassword/utils.js
lib/build/types.d.ts
lib/ts/recipe/emailpassword/components/library/label.tsx
lib/ts/recipe/emailpassword/components/themes/resetPasswordUsingToken/resetPasswordEmail.tsx
lib/ts/recipe/emailpassword/utils.ts
lib/ts/types.ts
test/end-to-end/resetpasswordusingtoken.test.js
test/end-to-end/signin-rrdv5.test.js
test/end-to-end/signin-rrdv6.test.js
test/end-to-end/signin.test.js
test/end-to-end/signup.test.js

Updated the reset password form to match the single input forms from passwordless.
+ Removed ":" from labels
-   #341 
Manual/visual tests
N/A …

Reset pw improvements

---

CHANGELOG.md
lib/build/recipe/thirdparty/components/themes/signInAndUpCallback/index.js
lib/build/version.d.ts
lib/build/version.js
lib/ts/recipe/thirdparty/components/themes/signInAndUpCallback/index.tsx
lib/ts/version.ts
package-lock.json
package.json

Removed SuperTokensBranding from the oauth callback screen
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch …

Removed SuperTokensBranding from the oauth callback screen

---

CHANGELOG.md
examples/with-account-linking/src/App.js
examples/with-emailpassword/src/App.js
examples/with-localstorage/src/App.js
examples/with-thirdparty/src/App.js
examples/with-thirdpartyemailpassword/src/App.js

There are 2 elements provided as the children of EmailPassword.EmailPasswordAuth, giving the error:
> This JSX tag's 'children' prop expects a single child of type 'Element', but multiple children were provided
Fixed it by adding a fragment.
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and …

fix: multiple children were provided error

---

CHANGELOG.md
lib/build/recipe/passwordless/types.d.ts
lib/build/version.d.ts
lib/build/version.js
lib/ts/recipe/passwordless/types.ts
lib/ts/version.ts
package-lock.json
package.json

Added `defaultCountry` to passwordless config input in the `EMAIL_OR_PHONE` case
-
Typing only change
N/A
-   If no such branch exists, then …

fix(passwordless): Add missing defaultCountry to input type

---

CHANGELOG.md
lib/build/recipe/thirdpartypasswordless/components/themes/signInUp/header.js
lib/ts/recipe/thirdpartypasswordless/components/themes/signInUp/header.tsx

Adding a divider below the thirdpartypasswordless header
-   #404 
Design only change
Design only change
-   If no such branch exists, then …

fix(thirdpartypasswordless): add missing header divider

---

CHANGELOG.md
lib/build/components/SuperTokensBranding.js
lib/build/version.d.ts
lib/build/version.js
lib/ts/components/SuperTokensBranding.tsx
lib/ts/version.ts
package-lock.json
package.json

- The branding component uses `https://supertokens.com?campaign=poweredby` as the `href`, this PR changes it to `https://supertokens.com?utm_campaign=poweredby` to make it adhere with UTM tracking
- 
- All existing test cases should pass (Github Actions)
- None needed
-   [ ] ~~`frontendDriverInterfaceSupported.json` file has been updated (if needed)~~
-   ~~Along with the associated array in `lib/ts/version.ts`~~
-   To know which one it is, run find the latest released tag (`git …

refactor: Rename query param in SuperTokens branding component to utm_campaign

---

lib/build/recipe/session/index.d.ts
lib/build/recipe/session/recipe.d.ts
lib/build/recipe/session/recipe.js
lib/build/recipe/session/types.d.ts
lib/ts/recipe/session/index.ts
lib/ts/recipe/session/recipe.ts
lib/ts/recipe/session/types.ts
package-lock.json
package.json

- Uses input types for session recipe from supertokens-web-js instead of redeclaring them
-   https://github.com/supertokens/for-zenhub/issues/28
- https://github.com/supertokens/supertokens-web-js/pull/24
Tests from Github actions should pass
None
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, …

refactor: Use web-js input type for session recipe

---

examples/for-tests/src/App.js
examples/with-sign-in-up-split-emailpassword/src/App.js
examples/with-thirdparty-2fa-passwordless/README.md
examples/with-thirdparty-2fa-passwordless/src/App.js
test/end-to-end/embed.test.js
test/end-to-end/userContext.test.js

- Use disableDefaultUI in query params during testing
- Use disableDefaultUI in the example apps
-   https://github.com/supertokens/for-zenhub/issues/28
All existing test cases should pass
WIP
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) …

refactor: Rename disableDefaultImplementation to disableDefaultUI in the query params in the testing environment and example apps

---

CHANGELOG.md
lib/build/recipe/session/recipe.js
lib/build/recipe/session/sessionAuth.js
lib/build/recipe/session/types.d.ts
lib/build/version.d.ts
lib/build/version.js
lib/ts/recipe/session/recipe.ts
lib/ts/recipe/session/sessionAuth.tsx
lib/ts/recipe/session/types.ts
lib/ts/version.ts
package-lock.json
package.json
test/unit/recipe/session/sessionAuth.test.tsx
test/with-typescript/src/App.tsx

Update session context when getting an `ACCESS_TOKEN_PAYLOAD_UPDATED` event
-   #397 
-   supertokens/supertokens-website#121 
Added unit test
supertokens/docs#324
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …

feat: update session context on ACCESS_TOKEN_PAYLOAD_UPDATED

---

lib/build/recipe/session/sessionAuth.js
lib/ts/recipe/session/sessionAuth.tsx

Remove an import I added by mistake
N/A
N/A
-   [x] If added a …

fix: remove accidental import

---

.circleci/config.yml

- Changes the Ubuntu image for CircleCI …

fix: Change Ubuntu image for CircleCI

---

.circleci/config_continue.yml

chore: For circleci use node 16 where needed

---

CHANGELOG.md
lib/build/version.d.ts
lib/build/version.js
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/passwordless.test.js
test/helpers.js

See title
-   https://github.com/supertokens/supertokens-auth-react/issues/490
-   If no such branch exists, then create one from the latest …

ci: adds new e2e test for resend code in passwordless recipe

---

CHANGELOG.md
examples/with-passwordless/package.json
examples/with-passwordless/src/Footer/index.js
examples/with-thirdpartyemailpassword-2fa-passwordless/src/SecondFactor/index.tsx
examples/with-thirdpartypasswordless/package.json
examples/with-thirdpartypasswordless/src/Footer/index.js

- Updates with-thirdpartypasswordless to call `getPasswordlessLoginAttemptInfo` from the index functions directly
- Update with-passwordless to call `getLoginAttemptInfo` from the index functions directly
- Updates with-thirdpartyemailpassword-2fa-passwordless to import from the default recipe export
-   ...
No logical changes
None
-   To know …

chore: Update example apps to use direct imports instead of build directories

---

test/server/index.js
test/server/utils.js

- Makes sure that the node SDK version is 10.0.0 or greater when enabling general errors
-   
-   If no such branch exists, then create one …

refactor: Add check for node sdk version when adding general error feature flag

---

.mocharc.yml
test/end-to-end/emailverification.test.js

- Fixed missing cleanup
- Remove exit=true from default mocha options to catch this locally
Test/ci only change
Test/ci only change
-   If no …

test: fix missing cleanup

---

lib/build/recipe/passwordless/utils.js
lib/ts/recipe/passwordless/utils.ts
test/end-to-end/passwordless.test.js

- Fixed phone number guesser adding a + to undefined/empty values
- Updated tests to match new behavior
-   
Not necessary
None necessary
- …

fix: pwless phone number guesser + tests

---

CHANGELOG.md
examples/for-tests-react-16/src/App.js
examples/for-tests/src/App.js
package-lock.json
package.json
test/end-to-end/getRedirectionURL.test.js

- Adds tests to make sure isNewUser is passed correctly for all recipes
-   https://github.com/supertokens/supertokens-auth-react/issues/519
NOTE: Some of the new tests fail, they will pass once https://github.com/supertokens/supertokens-web-js/pull/47 is merged and released
None
-   To know which one it is, run find the latest released tag …

chore: Add tests for isNewUser in getRedirectionURL context

---

test/end-to-end/getRedirectionURL.test.js
test/helpers.js

- Adds feature checks to make sure the tests dont run against a backend SDK version that doesnt support the Recipes
-   
-   To know which one it is, run find the latest released tag (`git tag`) …

fix: Add feature checks for passwordless and thirdpartypasswordless for getRedirectionUrl tests

---

CHANGELOG.md
examples/with-supabase/pages/_app.tsx
examples/with-supabase/pages/index.tsx

- changes to resolve supertokens-auth-react being updated to 0.24
-   https://github.com/supertokens/supertokens-core/issues/462
- manual testing
-   To know which one it is, run find the latest …

fix: migrates supabase app to supertokens-auth-react to 0.24

---

examples/with-okta-multi-tenant-pkce-flow/README.md
examples/with-okta-multi-tenant-pkce-flow/package.json
examples/with-okta-multi-tenant-pkce-flow/public/index.html
examples/with-okta-multi-tenant-pkce-flow/public/manifest.json
examples/with-okta-multi-tenant-pkce-flow/src/index.css
examples/with-okta-multi-tenant-pkce-flow/src/index.tsx
examples/with-okta-multi-tenant-pkce-flow/src/routes/dashboard.tsx
examples/with-okta-multi-tenant-pkce-flow/src/routes/index.tsx
examples/with-okta-multi-tenant-pkce-flow/src/setupTests.tsx
examples/with-okta-multi-tenant-pkce-flow/tsconfig.json
package.json

- applied prettier on new example
- updated scripts to only check staged files during pre-commit
-   
N/A, example only change
N/A, example only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest …

chore: apply prettier to new example

---

CHANGELOG.md
examples/with-emailpassword/README.md
examples/with-passwordless/README.md
examples/with-thirdparty/README.md
examples/with-thirdpartyemailpassword/README.md
examples/with-thirdpartypasswordless/README.md

- Removes the section of adding environment variables for nodemailer in the with-thirdpartypasswordless example app. The example no longer uses those variables so it was redundant
- Removes the section for production builds from 
- with-emailpassword
- with-thirdparty
- with-thirdpartyemailpassword
- with-passwordless
- with-thirdpartypasswordless
-   
No code changes
None
-   [x] Issue this PR against the latest …

refactor: Edit READMEs for example apps

---

examples/with-angular-thirdpartyemailpassword/README.md
examples/with-emailpassword/README.md
examples/with-emailverification-then-password-thirdpartyemailpassword/README.md
examples/with-emailverification-with-otp/README.md
examples/with-hasura-thirdpartyemailpassword/README.md
examples/with-i18next/README.md
examples/with-jwt-localstorage/README.md
examples/with-multiple-email-sign-in/README.md
examples/with-no-session-on-sign-up-thirdpartyemailpassword/README.md
examples/with-passwordless/README.md
examples/with-phone-password/README.md
examples/with-sign-in-up-split-emailpassword/README.md
examples/with-svelte-react-thirdpartyemailpassword/README.md
examples/with-thirdparty/README.md
examples/with-thirdpartyemailpassword-2fa-passwordless/README.md
examples/with-thirdpartyemailpassword-passwordless/README.md
examples/with-thirdpartyemailpassword/README.md
examples/with-thirdpartypasswordless-electron/README.md
examples/with-thirdpartypasswordless/README.md
examples/with-vue-thirdpartyemailpassword/README.md

Add commands in the README to clone and enter the example dirs swiftly
-   [ ] Had …

feat: Add commands in the README to clone and enter the example dirs swiftly

---

examples/with-angular-thirdpartyemailpassword/README.md
examples/with-emailpassword/README.md
examples/with-emailverification-then-password-thirdpartyemailpassword/README.md
examples/with-emailverification-with-otp/README.md
examples/with-hasura-thirdpartyemailpassword/README.md
examples/with-i18next/README.md
examples/with-jwt-localstorage/README.md
examples/with-multiple-email-sign-in/README.md
examples/with-no-session-on-sign-up-thirdpartyemailpassword/README.md
examples/with-passwordless/README.md
examples/with-phone-password/README.md
examples/with-sign-in-up-split-emailpassword/README.md
examples/with-svelte-react-thirdpartyemailpassword/README.md
examples/with-thirdparty/README.md
examples/with-thirdpartyemailpassword-2fa-passwordless/README.md
examples/with-thirdpartyemailpassword-passwordless/README.md
examples/with-thirdpartyemailpassword/README.md
examples/with-thirdpartypasswordless-electron/README.md
examples/with-thirdpartypasswordless/README.md
examples/with-vue-thirdpartyemailpassword/README.md

Fix step in examples README to cd into supertokens-auth-react dir
-   [ ] Had installed …

fix: Fix step in examples README to cd into supertokens-auth-react dir

---

CHANGELOG.md
lib/build/recipe/thirdparty/providers/github.js
lib/ts/recipe/thirdparty/providers/github.tsx
test/helpers.js

Fix how we capitalize GitHub on the UI (API remains unchanged)
-   #539 
Updated string in tests
N/A
-   If no such branch exists, then create …

fix: GitHub casing

---

CHANGELOG.md
lib/build/utils.js
lib/ts/utils.ts

Rethrow errors that occur in the `fetch` part of `useOnMountAPICall` if no handler is added.
Rationale: This will result in the render throwing, and potentially the entire react tree being unmounted (e.g., if the server/ST core goes down), but also allows the user to add an error boundary that can handle the error and provide a meaningful error screen.
Matches the philosophy of React on unhandled errors: https://reactjs.org/docs/error-boundaries.html#new-behavior-for-uncaught-errors
-   #547
Not sure how we could test this meaningfully.
Not necessary, but we could advise adding an error boundary.
-   [x] Changes to …

feat!: rethrow errors occuring during onmount async calls

---

lib/build/recipe/thirdparty/index.d.ts
lib/build/recipe/thirdparty/index.js
lib/build/recipe/thirdparty/recipe.d.ts
lib/build/recipe/thirdpartyemailpassword/index.d.ts
lib/build/recipe/thirdpartyemailpassword/index.js
lib/build/recipe/thirdpartyemailpassword/recipe.d.ts
lib/build/recipe/thirdpartyemailpassword/recipe.js
lib/build/recipe/thirdpartypasswordless/index.d.ts
lib/build/recipe/thirdpartypasswordless/index.js
lib/build/recipe/thirdpartypasswordless/recipe.d.ts
lib/build/recipe/thirdpartypasswordless/recipe.js
lib/ts/recipe/thirdparty/index.ts
lib/ts/recipe/thirdparty/recipe.tsx
lib/ts/recipe/thirdpartyemailpassword/index.ts
lib/ts/recipe/thirdpartyemailpassword/recipe.tsx
lib/ts/recipe/thirdpartypasswordless/index.ts
lib/ts/recipe/thirdpartypasswordless/recipe.tsx
test/unit/exports.test.tsx

- removed remaining email verification references from other recipes
- updated exports test
-   
Updated a test
N/A
-   If no such branch …

feat: remove remaining emailverification references

---

lib/build/recipe/session/index.d.ts
lib/build/recipe/session/useClaimValue.d.ts
lib/build/recipe/session/useClaimValue.js
lib/ts/recipe/session/useClaimValue.ts
test/unit/recipe/session/sessionAuth.test.tsx

Added `doesSessionExist` to the return type of `useClaimValue`
-   #558 
Extended existing tests for the new prop
Done separately
-   If no …

feat: useClaimValue w/ doesSessionExist

---

CHANGELOG.md
lib/build/recipe/thirdpartypasswordless/index.d.ts
lib/ts/recipe/thirdpartypasswordless/index.ts
test/with-typescript/src/App.tsx

`ThirdPartyPasswordless.consumePasswordlessCode` expects an input even though it can be called without passing any arguments. This PR makes the input optional to make this experience better
-   
-   In …

refactor: Fix types for thirdpartypasswordless consumePasswordlessCode

---

examples/with-phone-password/src/PhoneVerification/index.tsx
examples/with-thirdpartyemailpassword-2fa-passwordless/src/App.tsx
examples/with-thirdpartyemailpassword-2fa-passwordless/src/SecondFactor/index.tsx

Re-add removing the change phone number footer to the 2fa example.
-   
N/A example only test
N/A example only test
-   If no such branch …

fix: session claims 2fa example

---

CHANGELOG.md
lib/build/recipe/emailpassword/components/themes/styles/styles.js
lib/ts/recipe/emailpassword/components/themes/styles/styles.ts

Fixing the colors of prefilled inputs
-   #567
Manual test (visual change only).
Before:
After:
N/A
-  To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the latest released tag.
-   If no such branch exists, then create …

fix: fix color of prefilled inputs

---

examples/for-tests-react-16/src/App.js

fix typo in react16 test app to fix getRedirectURL tests
-   
N/A, test fix
N/A, test fix
-   If no such branch exists, then create one from …

test: fix react16 get redirect tests

---

package-lock.json

Update dependencies in package-lock, to remove references of not existing branches
-   
N/A
N/A
-   If no such branch exists, then create one …

chore: update deps in package lock

---

CHANGELOG.md
init.sh
test/end-to-end/emailverification.test.js
test/prepTestApp.sh

Fix test & CI scripts to use updated website version
-   
N/A
N/A
-   [x] If added a new recipe interface, then make sure …

test: fix ci&scripts to use updated website version

---

CHANGELOG.md
lib/build/recipe/emailpassword/components/library/input.js
lib/build/recipe/passwordless/components/features/linkClickedScreen/index.js
lib/ts/recipe/emailpassword/components/library/input.tsx
lib/ts/recipe/passwordless/components/features/linkClickedScreen/index.tsx
test/end-to-end/passwordless.test.js
test/helpers.js

- Now the value of input can be controlled, fixing how we clear user inputs after submit
- Fixed error message on unknown/network errors while consuming link codes
-   #587
- Added a test case for network errors while consuming links
- Modified a test case to check that the OTP input gets cleared after each submit
N/A, fixes only
-   To know which one it is, run find the latest released tag (`git tag`) …

fix: pwless small issues

---

CHANGELOG.md
lib/build/recipe/thirdparty/components/themes/signInAndUp/index.js
lib/build/recipe/thirdparty/components/themes/signInAndUp/signInAndUpHeader.d.ts
lib/build/recipe/thirdparty/components/themes/signInAndUp/signInAndUpHeader.js
lib/build/recipe/thirdparty/types.d.ts
lib/build/recipe/thirdpartypasswordless/types.d.ts
lib/ts/recipe/thirdparty/components/themes/signInAndUp/index.tsx
lib/ts/recipe/thirdparty/components/themes/signInAndUp/signInAndUpHeader.tsx
lib/ts/recipe/thirdparty/types.ts
lib/ts/recipe/thirdpartypasswordless/types.ts
test/unit/componentOverrides.test.tsx

make the thirdparty login form header overrideable
-  
Added to override tests.
Manually tested in the thirdparty example
Not necessary (the example in the documentation uses the footer)
-   If no such …

feat: make the thirdparty login form header overrideable

---

CHANGELOG.md
lib/build/recipe/passwordless/components/themes/signInUp/emailOrPhoneForm.js
lib/ts/recipe/passwordless/components/themes/signInUp/emailOrPhoneForm.tsx
test/end-to-end/passwordless.test.js

Updated passwordless login to first try calling the API if it could guess a valid international phone number
-   #602 
Updated test + added unit test
N/A
-   [x]Issue this PR against the latest non released version branch.
-   If no such branch exists, then create one …

feat: pwless phone or email call API with guessed phone number

---

test/end-to-end/passwordless.test.js

Skipping the new passwordless test case in react 16.
-   #605 
N/A
N/A
-   [x] If added a new recipe interface, then make …

test: fix pwless e2e tests react 16

---

package-lock.json
package.json

Update the main size-limit dependency to match the preset
-   
N/A
N/A
-   [x] If added a new recipe interface, then make …

chore: update size-limit

---

CHANGELOG.md
lib/build/passwordless-shared.js
lib/build/version.d.ts
lib/ts/recipe/passwordless/validators.ts
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/passwordless.test.js

-   Fixed guessing internation phone number in passwordless with EMAIL_OR_PHONE contact method if the number starts with a valid country dial code
Added tests for invalid phone numbers that start with a valid dial code
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git …

fix: guess phone number ux

---

examples/for-tests-react-16/src/AppWithReactDomRouter.js
examples/for-tests-react-16/src/AppWithReactDomRouterV5.js
examples/for-tests-react-16/src/AppWithoutRouter.js
examples/for-tests/src/AppWithoutRouter.js

- fix react16 tests
- fix small inconsistencies between test apps
-   [ ] Issue this PR against the …

test: fix react16 tests

---

package-lock.json
test/server/index.js

- update test server to support renamed getSessionData
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-auth-react/3469/workflows/9fe8a434-2bba-4280-b1f6-a7139c4934e6/jobs/1946
Test only update
Test only update
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater …

test: update test server to support renamed getSessionData

---

CHANGELOG.md
examples/for-tests-react-16/package.json
examples/for-tests/package.json
lib/build/emailverificationprebuiltui.js
lib/ts/recipe/emailverification/components/themes/emailVerification/index.tsx
package-lock.json
package.json

- locks react-router-dom version at 6.11.2 (we need to provide a proper fix for issues with 6.12)
- blocks rendering the send verify screen without a session (partial fix for react-router-dom 6.12 issues)
-   https://app.circleci.com/pipelines/github/supertokens/supertokens-auth-react/3572/workflows/42048692-2744-4206-aa7c-626f49fe7f11
Fixes only
N/A
-   To know which one it is, run find the latest …

fix: do not render send verify without session

---

examples/with-thirdpartypasswordless-electron/package.json

- Fixes the plugins structure in the package json for the electron example app
- ...
NA
NA
-   [ ] If added a new recipe …

fix: Fix node plugins config for electron example app

---

examples/for-tests-react-16/src/App.js
examples/for-tests-react-16/src/testContext.js
examples/for-tests/src/App.js
examples/for-tests/src/testContext.js
test/end-to-end/thirdparty.test.js
test/end-to-end/thirdpartyemailpassword.test.js

add tests checking if clientType is applied in tp, tpep and tppwless recipes
-   https://github.com/supertokens/supertokens-web-js/pull/96
Tests only change
Tests only change
-   If no such branch …

test: add tests checking if clientType is applied in tp, tpep and tppwless recipes

---

CHANGELOG.md
examples/for-tests-react-16/src/testContext.js
examples/for-tests/src/testContext.js
lib/build/thirdparty-shared.js
lib/build/thirdparty-shared2.js
lib/build/version.d.ts
lib/ts/recipe/thirdparty/components/features/signInAndUp/index.tsx
lib/ts/recipe/thirdparty/utils.ts
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/multitenancy.dynamic_login_methods.test.js

Fixed the SDK trying to merge the providers from the tenant config if the third party login method is disabled.
-   https://github.com/supertokens/supertokens-golang/pull/342
Added tests where: only one combination recipe is enabled on the frontend w/ one of the login methods disabled
N/A
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the …

fix: handle null in provider list of the tenant config

---

CHANGELOG.md
lib/build/version.d.ts
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/accountlinking.test.js
test/end-to-end/emailverification.test.js
test/end-to-end/embed.test.js
test/end-to-end/generalerror.test.js
test/end-to-end/getRedirectionURL.test.js
test/end-to-end/multitenancy.dynamic_login_methods.test.js
test/end-to-end/multitenancy.tenant_interactions.test.js
test/end-to-end/passwordless.test.js
test/end-to-end/resetpasswordusingtoken.test.js
test/end-to-end/signin-rrdv5.test.js
test/end-to-end/signin-rrdv6.test.js
test/end-to-end/signin.test.js
test/end-to-end/signup.test.js
test/end-to-end/thirdparty.test.js
test/end-to-end/thirdpartyemailpassword.test.js
test/end-to-end/thirdpartypasswordless.test.js
test/end-to-end/userContext.test.js
test/end-to-end/userroles.test.js
test/helpers.js

test: fix test in backend SDK ci
-   CI run failures
Test only change
Test only change
-   [x] If added a new recipe …

test: fix test in backend SDK ci

---

CHANGELOG.md
lib/build/thirdparty-shared.js
lib/build/version.d.ts
lib/ts/recipe/thirdparty/providers/twitter.tsx
lib/ts/version.ts
package-lock.json
package.json

fixes twitter Id Issue
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch --all`) whose `X.Y` is greater than the …

fix: use twitter as twitter providers Id

---

CHANGELOG.md
lib/build/index2.js
lib/build/version.d.ts
lib/ts/components/featureWrapper.tsx
lib/ts/version.ts
package-lock.json
package.json

Only attach a shadow root if it hasn't been one already attached. This fixes an issue in NextJS dev mode that required disabling shadowDom
- 
Manual testing in NextJS example dev mode
N/A
-   If no such …

fix: only add shadow root if there is none attached

---

examples/for-tests/src/App.js
lib/build/emailpassword-shared4.js
lib/build/emailpassword-shared7.js
lib/build/recipe/emailpassword/components/themes/resetPasswordUsingToken/submitNewPassword.d.ts
lib/build/recipe/emailpassword/components/themes/signInAndUp/signIn.d.ts
lib/build/recipe/emailpassword/components/themes/signInAndUp/signUp.d.ts
lib/build/recipe/thirdpartyemailpassword/components/themes/translations.d.ts
lib/build/recipe/thirdpartypasswordless/components/themes/translations.d.ts
lib/build/types.d.ts
lib/ts/recipe/emailpassword/components/library/formBase.tsx
lib/ts/recipe/emailpassword/utils.ts
lib/ts/types.ts
test/end-to-end/signin.test.js
test/end-to-end/signup.test.js
test/with-typescript/src/App.tsx

Modified the sign-in and sign-up form fields to accept a new property: `nonOptionalErrorMsg`. 
This allows for the display of a custom error message specified by the user, instead of the default `Field is not Optional` message, for fields that are mandatory.
-   [Field decorators #36](https://github.com/supertokens/supertokens-auth-react/issues/36)
- …

feat: add nonOptionalErrorMsg props 

---

CHANGELOG.md
examples/for-tests/src/App.js
examples/for-tests/src/testContext.js
lib/build/emailpassword-shared7.js
lib/build/version.d.ts
lib/ts/recipe/emailpassword/components/library/label.tsx
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/signin.test.js
test/end-to-end/signup.test.js
test/end-to-end/thirdpartyemailpassword.test.js

Fixes and feedbacks from [this PR](https://github.com/supertokens/supertokens-auth-react/pull/760) …

fix: display required indicator only for non-empty labels and Improve test structure

---

test/end-to-end/signin.test.js
test/end-to-end/signup.test.js
test/end-to-end/thirdpartyemailpassword.test.js

Handle react 16 tests for new features

---

test/end-to-end/signin-rrdv5.test.js

fix: failing tests, now ensures correct recipe is set in the backend

---

CHANGELOG.md
lib/build/recipe/emailpassword/components/themes/resetPasswordUsingToken/submitNewPassword.d.ts
lib/build/recipe/emailpassword/components/themes/signInAndUp/signIn.d.ts
lib/build/recipe/emailpassword/components/themes/signInAndUp/signUp.d.ts
lib/build/recipe/thirdpartyemailpassword/components/themes/translations.d.ts
lib/build/recipe/thirdpartypasswordless/components/themes/translations.d.ts
lib/build/thirdparty-shared2.js
lib/build/thirdpartyemailpasswordprebuiltui.js
lib/build/version.d.ts
lib/ts/recipe/thirdpartyemailpassword/components/themes/signInAndUp/index.tsx
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/multitenancy.dynamic_login_methods.test.js

Fixes ThirdPartyEmailPassword rendering sign in/up switcher even with disabled email password. 
Instead it'll now render `SignInAndUpHeader` in this case (overrideable as `ThirdPartySignInAndUpHeader`)
-   Issue reported on discord
Updated existing test to check the header
-
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch …

fix: tpep header with disabled emailpassword

---

CHANGELOG.md
lib/build/recipe/emailpassword/components/themes/resetPasswordUsingToken/submitNewPassword.d.ts
lib/build/recipe/emailpassword/components/themes/signInAndUp/signIn.d.ts
lib/build/recipe/emailpassword/components/themes/signInAndUp/signUp.d.ts
lib/build/recipe/thirdpartyemailpassword/components/themes/signInAndUp/header.d.ts
lib/build/recipe/thirdpartyemailpassword/components/themes/translations.d.ts
lib/build/recipe/thirdpartypasswordless/components/themes/translations.d.ts
lib/build/thirdpartyemailpasswordprebuiltui.js
lib/ts/recipe/thirdpartyemailpassword/components/themes/signInAndUp/header.tsx
lib/ts/recipe/thirdpartyemailpassword/components/themes/signInAndUp/index.tsx

move SignInAndUpHeader inside ThirdPartyEmailPasswordHeader to improve overrides
-   [ ] Issue this …

fix: move SignInAndUpHeader inside ThirdPartyEmailPasswordHeader to improve overrides

---

test/end-to-end/passwordless.test.js

This PR fixes e2e tests that broke due to removal of success screen in #766 
Tested the breaking e2e tests locally. 
-   [ …

fix: breaking e2e tests due to removal of success screen

---

CHANGELOG.md
lib/build/genericComponentOverrideContext.js
lib/build/utils.d.ts
lib/build/version.d.ts
lib/ts/superTokens.tsx
lib/ts/utils.ts
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/emailverification.test.js
test/end-to-end/passwordless.test.js
test/end-to-end/signin.test.js
test/end-to-end/signup.test.js
test/end-to-end/thirdparty.test.js
test/helpers.js

Previously, when calling `redirectToAuth` with the `redirectBack` option, query parameters were stripped when redirecting back to the previous page after authentication. This issue has been fixed, and now query parameters are preserved as intended.
Tested manually extensively. Also, updated an existing test case to verify query params are being preserved. 
-   To know which one it is, run find the …

fix: preserve query params when redirectBack is used

---

lib/build/index2.js
lib/build/recipe/session/sessionAuth.d.ts
lib/build/recipe/session/types.d.ts
lib/ts/recipe/session/index.ts
lib/ts/recipe/session/sessionAuth.tsx
lib/ts/recipe/session/types.ts
package-lock.json
recipe/session/index.js
test/unit/componentOverrides.test.tsx
test/unit/recipe/emailpassword/signInUp.test.tsx
test/unit/recipe/passwordless/signInUp.test.tsx
test/unit/recipe/session/sessionAuth.test.tsx
test/unit/recipe/thirdparty/signInUp.test.tsx
test/unit/recipe/thirdpartyemailpassword/signInUp.test.tsx
test/unit/recipe/thirdpartypasswordless/signInUp.test.tsx

Adds `initialSessionAuthContext` support for `SessionAuth` component. `initialSessionAuthContext` is an initial state that Session provider uses to create a context.
- Added `initialSessionAuthContext` property to `SessionAuthProps`
- Added `isContextFromSSR` to `LoadedSessionContext` that signals if a session context is provided from a server or computed on the client.
-  `isContextFromSSR: true`  when uses initial context preloaded from server (SSR). This means `invalidClaims[]` and `accessDeniedValidatorError` are not yet evaluated and the client should not trust the data (as discussed with @porcellus ) 
-  `isContextFromSSR: false`  when uses a client generated context (ex: after client rerender)
-   https://github.com/supertokens/supertokens-auth-react/issues/790
- …

feat: SessionAuth SSR support (initialSessionAuthContext)

---

CHANGELOG.md
lib/build/dateProvider/index.d.ts
lib/build/dateProvider/types.d.ts
lib/build/genericComponentOverrideContext.js
lib/build/types.d.ts
lib/build/version.d.ts
lib/ts/dateProvider/index.ts
lib/ts/dateProvider/types.ts
lib/ts/types.ts
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/emailverification.test.js
test/unit/dateProvider.test.ts
test/with-typescript/src/App.tsx
utils/dateProvider/index.d.ts
utils/dateProvider/index.js
utils/dateProvider/types.d.ts
utils/dateProvider/types.js

This PR adds `dateProvider` as a config  that is used to fix clock skew issues between server and client.
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, and then find the latest branch (`git branch …

feat: add dateProvider config

---

package.json
test/unit/recipe/session/sessionAuth.test.tsx
test/unit/recipe/thirdparty/thirdParty.test.ts

test: update unit tests to match new behaviour from PR #811 
-   #811 
N/A, test only update
N/A, test only update
-   [ ] …

test: update unit tests to match new behaviour from PR#811

---

test/end-to-end/mfa.chooserscreen.test.js
test/end-to-end/mfa.default_reqs.test.js
test/end-to-end/mfa.factorscreen.otp.test.js
test/end-to-end/mfa.factorscreen.totp.test.js
test/end-to-end/mfa.requirement_handling.test.js
test/end-to-end/mfa.signin.test.js

Fix import errors introduced by #813 (vscode moved and supposedly updated imports but it didn't actually happen)
-   [CI failures](https://app.circleci.com/pipelines/github/supertokens/supertokens-auth-react/4389/workflows/9795cc80-5f58-4e9f-8792-c21879253e23/jobs/2433)
N/A test only change
N/A test only change
-   To know which one it is, run find the latest released tag (`git tag`) in the format …

test: fix import errors in e2e tests

---

lib/build/passwordlessprebuiltui.js
lib/ts/recipe/passwordless/components/themes/userInputCodeForm/userInputCodeFormScreen.tsx
stories/emailverification.stories.tsx
test/end-to-end/mfa.helpers.js
test/end-to-end/passwordless.allrecipes.email.test.js
test/end-to-end/passwordless.allrecipes.email_or_phone.test.js
test/end-to-end/passwordless.allrecipes.phone.test.js
test/end-to-end/passwordless.email.test.js
test/end-to-end/passwordless.email_or_phone.test.js
test/end-to-end/passwordless.phone.test.js
test/end-to-end/passwordless.test_gen.js
test/end-to-end/thirdpartypasswordless.pwless.email.test.js
test/end-to-end/thirdpartypasswordless.pwless.email_or_phone.test.js
test/end-to-end/thirdpartypasswordless.pwless.phone.test.js
test/helpers.js

fix: missing branding from OTP screen
test parallelization&stability improvements
storybooks fix
- …

fix: missing branding from OTP screen

---

CHANGELOG.md
examples/for-tests-react-16/src/App.js
examples/for-tests-react-16/src/testContext.js
examples/for-tests/src/App.js
examples/for-tests/src/testContext.js
lib/build/genericComponentOverrideContext.js
lib/build/index2.js
lib/build/version.d.ts
lib/ts/recipe/session/sessionAuth.tsx
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/signin.test.js

skip unnecessary updates in SessionAuth
-   
Added an extra test that replacates a case we've seen on a user call: running signout on context updates that have `doesSessionExist === false`. This used to trigger an infinite re-render loop.
None, this is a small optimization that people should not rely on.
-   To know which one it is, run find the latest released tag (`git tag`) in the format `vX.Y.Z`, …

feat: skip unnecessary updates in SessionAuth

---

CHANGELOG.md
addDevTag
lib/build/genericComponentOverrideContext.js
lib/build/version.d.ts
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/accountlinking.test.js

fix: e2e with 0.41

---

CHANGELOG.md
lib/build/genericComponentOverrideContext.js
lib/build/index2.js
lib/build/version.d.ts
lib/ts/recipe/authRecipe/components/feature/authPage/authPage.tsx
lib/ts/version.ts
package-lock.json
package.json

Added a more detailed error message in cases where we have more specific info.
-   [Discord convo](https://discord.com/channels/603466164219281420/1269943257060737085)
-   To know which one it is, run find the latest released tag (`git tag`) in the …

fix: improve error messages when the authpage has issues covering all factors

---

CHANGELOG.md
examples/for-tests-react-16/src/App.js
examples/for-tests/src/App.js
examples/with-multifactorauth-phone-chooser/frontend/package.json
examples/with-multifactorauth-phone-chooser/frontend/src/Home/CallAPIView.tsx
examples/with-multifactorauth-phone-chooser/frontend/src/SelectPhone/index.tsx
examples/with-multifactorauth-recovery-codes/frontend/src/RecoveryCode/index.tsx
lib/build/genericComponentOverrideContext.js
lib/build/multifactorauth-shared2.js
lib/build/multifactorauth.js
lib/build/multifactorauthprebuiltui.js
lib/build/passwordlessprebuiltui.js
lib/build/recipe/multifactorauth/index.d.ts
lib/build/recipe/multifactorauth/recipe.d.ts
lib/build/recipe/multifactorauth/types.d.ts
lib/build/totpprebuiltui.js
lib/build/version.d.ts
lib/ts/recipe/multifactorauth/components/features/factorChooser/index.tsx
lib/ts/recipe/multifactorauth/index.ts
lib/ts/recipe/multifactorauth/recipe.tsx
lib/ts/recipe/multifactorauth/types.ts
lib/ts/recipe/passwordless/components/features/mfa/index.tsx
lib/ts/recipe/totp/components/features/mfa/index.tsx
lib/ts/version.ts
package-lock.json
package.json
test/end-to-end/mfa.factorscreen.otp.test.js
test/end-to-end/mfa.factorscreen.totp.test.js

-   Changed `redirectToFactor` to accept an object instead of multiple arguments.
-   Changed `redirectToFactorChooser` to accept an object instead of multiple arguments.
-   Made MFA related screens do a success redirection if MFA is already completed and the `stepUp` query param is not set to `true`.
-   `redirectToFactorChooser` now accepts a `stepUp` option to set the `stepUp` query param.
-   `redirectToFactor` now accepts a `stepUp` option to set the `stepUp` query param.
-   
Updated existing tests/the test app to use the stepUp query param by default
Added new tests that check the redirection happens if the new query param is not added
Docs [PR](https://github.com/supertokens/docs/pull/836)
-   [x] `frontendDriverInterfaceSupported.json` file has …

 feat!: make the mfa screens do success redirection if the next array is empty

---

CHANGELOG.md
lib/build/passwordless-shared.js
lib/build/passwordlessprebuiltui.js
lib/build/recipe/passwordless/utils.d.ts
lib/ts/recipe/passwordless/components/features/mfa/index.tsx
lib/ts/recipe/passwordless/prebuiltui.tsx
lib/ts/recipe/passwordless/utils.ts

This is a convenience thing for people migrating from custom UI to prebuilt UI which we do not test for
N/A
-   If no such …

feat!: make passwordless link sent, otp input and mfa screens clear the login attempt info if it is missing some props

---

CHANGELOG.md
lib/build/ui/types.d.ts
lib/ts/ui/types.ts
test/with-typescript/src/App.tsx

-   [x] Issue this PR against the latest non released version …

fix: add SessionPreBuiltUI into PreBuiltRecipes

---

test/end-to-end/emailverification.test.js
test/helpers.js

Fixes the CI test failure
- All failing tests(CI) now pass locally
-   [ ] Issue this PR against …

test: fix CI test failure

---

CHANGELOG.md
lib/build/genericComponentOverrideContext.js
lib/build/passwordlessprebuiltui.js
lib/build/version.d.ts
lib/ts/recipe/passwordless/components/features/signInAndUpEPCombo/index.tsx
lib/ts/version.ts
package-lock.json
package.json

Fixed an issue where we showed the "continue with passwordless" button during sign-in even if email-based passwordless was disabled by the tenant configuration.
-   
-   To know which one it is, run find the latest released tag (`git tag`) in the format …

fix: only show continue with passwordless if email pwless is enabled

---

lib/build/recipe/oauth2provider/index.d.ts
lib/build/recipe/oauth2provider/recipe.d.ts
lib/ts/recipe/oauth2provider/index.ts
lib/ts/recipe/oauth2provider/recipe.ts

fix: add missing types to OAuth2Provider recipe init

---

lib/build/index2.js
lib/build/oauth2providerprebuiltui.js
lib/ts/recipe/authRecipe/components/feature/authPage/authPage.tsx
lib/ts/recipe/oauth2provider/components/features/oauth2LogoutScreen/index.tsx
test/end-to-end/oauth2provider.test.js

fix: better error handling in oauth flows

---

CHANGELOG.md
lib/build/passwordlessprebuiltui.js
lib/build/recipe/passwordless/types.d.ts
lib/build/recipe/recipeModule/index.d.ts
lib/ts/recipe/passwordless/components/features/signInAndUpEPCombo/index.tsx
lib/ts/recipe/passwordless/components/themes/signInUpEPCombo/emailForm.tsx
lib/ts/recipe/passwordless/components/themes/signInUpEPCombo/emailOrPhoneForm.tsx
lib/ts/recipe/passwordless/types.ts
lib/ts/recipe/recipeModule/index.ts
test/end-to-end/passwordless.test_gen.js

fix: use navigate fn to redirect to reset pw page in ep+pwless combo

---

examples/for-tests-react-16/src/App.js
examples/for-tests/src/App.js
test/end-to-end/generalerror.test.js
test/end-to-end/getRedirectionURL.test.js
test/end-to-end/multitenancy.dynamic_login_methods.test.js
test/end-to-end/thirdparty.test.js
test/end-to-end/thirdpartyemailpassword.test.js
test/end-to-end/thirdpartypasswordless.test.js
test/end-to-end/thirdpartypasswordless.tp.test.js
test/end-to-end/userContext.test.js
test/helpers.js

test: switch to mock provider

---

lib/build/webauthnprebuiltui.js
lib/ts/recipe/webauthn/components/features/signIn/index.tsx
test/end-to-end/webauthn.recover_account.test.js
test/end-to-end/webauthn.recovery_email.test.js
test/end-to-end/webauthn.signin.test.js
test/end-to-end/webauthn.signup.test.js

This PR updates webauthn tests to make them pass based on the updated code changes for showBackButton and general error component usage.
All Webauthn tests should pass
-   To know which one it is, run find the latest released tag (`git tag`) in the …

fix: Webauthn test updates due to changes

---

CHANGELOG.md
lib/build/genericComponentOverrideContext.js
lib/build/ui/types.d.ts
lib/build/version.d.ts
lib/ts/ui/types.ts
lib/ts/version.ts
package-lock.json
package.json

Add missing type for the `getRoutingComponent` argument.
-   [ ] Issue this PR against the latest …

fix: Include missing webauthn type

---

test/end-to-end/generalerror.test.js
test/end-to-end/getRedirectionURL.test.js
test/end-to-end/mfa.chooserscreen.test.js
test/end-to-end/mfa.helpers.js
test/end-to-end/mfa.requirement_handling.test.js
test/end-to-end/mfa.signin.test.js
test/end-to-end/multitenancy.tenant_interactions.test.js
test/end-to-end/passwordless.test.js
test/end-to-end/thirdpartyemailpassword.test.js
test/helpers.js

fix: failing auth-react tests [0.41]

---

test/end-to-end/generalerror.test.js
test/end-to-end/getRedirectionURL.test.js
test/end-to-end/thirdpartyemailpassword.test.js
test/helpers.js

fix: failing auth-react tests [0.38]
